name: Swiftlint

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build and Run
      run: |
        brew install swiftlint
        swiftlint
